### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by shinoshyun**
my name : 陳筱璇
thank teacher's help~~and classmates~
http://13.114.36.224:3000/api/attractions?page=1
http://13.114.36.224:3000/api/attractions?page=0&keyword=藝文館所
http://13.114.36.224:3000/api/attractions?page=0&keyword=北
http://13.114.36.224:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Based on our data, `nextPage` of http://13.114.36.224:3000/api/attractions?page=2 should not be `null`.

Solve this issue and re-request review.

**Comment by shinoshyun** [comment]
teacher I fix it~
thank you!

http://13.114.36.224:3000/api/attractions?page=1
http://13.114.36.224:3000/api/attractions?page=0&keyword=藝文館所
http://13.114.36.224:3000/api/attractions?page=0&keyword=北
http://13.114.36.224:3000/api/attraction/10

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by shinoshyun** [comment]
還以為關掉就不能回覆了!!耶~~謝謝老師~~~

**Pull request merged**
